### ISSUE TITLE
Standardize NPM Version Used for Fundamental-React

### ISSUE THREAD

**Issue by jeffredodd** [SAP/fundamental-react#170]
In order to reduce changes to `package-lock.json` we should pick a version of NPM/Node to use for this library. Can we standardize the version of Node/NPM for this repo? 

Possible Questions ❓ 
- What version would people like?
- Is everyone comfortable with `nvm` to manage Node/NPM version?
- Can we also use this standard for Travis Builds. 

This issue should be resolved once we have locked on a version.

**Comment by greg-a-smith** [comment]
Between versions 5 and 6 of `npm`, they changed the way the `package-lock.json` file is written.  So, if this file gets committed by someone using version 6, then anyone using version 5 will see this file as being modified anytime you run `npm install` (even when there are no changes in `package.json`).  The same would occur if it were committed using version 5 and someone else was using version 6.

Since it sounds like the Hybris team as already been using `npm` v6.x.x, should that be the standard?

**Comment by bcullman** [comment]
We should standardize on the LTS version of node (currently at 10.15.0). See: https://nodejs.org/en/

This version of node brings npm 6.4.1 along for the ride.

**Comment by droshev** [comment]
@bcullman is there something we need to ask the admins to enable in Travis or we can do it?
