### ISSUE TITLE
Consider implementing prettier for automatic code formatting

### ISSUE THREAD

**Issue by mobot11** [SAP/fundamental-react#179]
https://prettier.io/ is an automatic JavaScript code formatter. It can make working in open source repos less painful by automatically enforcing code style guidelines with no effort. Also has integrations for many popular editors.

**Comment by chrismanciero** [comment]
If you are developing with VS Code there is a prettier extension that allows you to change the settings so that the eslint rules can be automatically applied to files changed on save.

<img width="945" alt="screen shot 2019-01-11 at 2 37 14 pm" src="https://user-images.githubusercontent.com/38330612/51055640-6dac1e00-15ae-11e9-836d-3cb3299ebd91.png">

**Comment by jiawang1** [comment]
it would be better add perttier config into project to make sure all contributors using unified configuration but not depends on their IDE.

**Comment by bcullman** [comment]
@chrismanciero and i have discovered that even you use prettier in combination with ESList it is problematic.

Essentially, prettier respects ESLint rules. but for anything that is not covered by ESLint rules, prettier will rewrite the code based on *it's* default settings.  This causes unnecessary diff's in PRs.

A better solution is to have all formatting backed by ESLint rules, And use the ESLint extension for your respective Code Editor. That way there is no *magic* code rewriting.

**Comment by mobot11** [comment]
I'll go ahead and close this one then. I think we can get by fine with just eslint.
