### ISSUE TITLE
automation/unit test POC

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-react#30]
Create a strategy for automation/unit tests per components

**Comment by chrismanciero** [comment]
@droshev - I started looking into unit testing components with Jest and Enzyme. I create a feature branch (https://github.com/SAP/fundamental-react/tree/unit-testing) which has my unit tests for the MultiInput component and SearchInput controls (both are now at 100% code coverage).

Running **npm test**:
<img width="423" alt="screen shot 2018-11-09 at 6 51 50 pm" src="https://user-images.githubusercontent.com/38330612/48294146-8a15c800-e450-11e8-900e-2dbd4901feba.png">

Running **npm test -- --coverage** will give a code coverage report.

App.test.js fails because of the way the Routes are setup, have to do more research on trying to fix it. I think it has to do more with the testing setup than the functionality.

**Comment by chrismanciero** [comment]
@droshev @InnaAtanasova Should this story be closed since all components have unit test and we have the automated tests setup with the builds?
