### ISSUE TITLE
Edge detection for popover-style elements

### ISSUE THREAD

**Issue by bcullman** [SAP/fundamental-react#313]
### Description
Edge detection for popover-style elements

### Versions
**fundamental-react: 0.2.X**
**fiori-fundamentals: 1.4.1**

---
popovers (and other popup style components. should edge-detect and flip where there is no space.

[popperjs](https://popper.js.org/) / [popperjs github](https://github.com/FezVrasta/popper.js) provides this functionality, and has libraries to react, angular and vue. 

https://www.npmjs.com/package/react-popper
https://www.npmjs.com/package/ngx-popper
https://www.npmjs.com/package/vue-popperjs

SAP Concur has previously had good success with popper.js, and implemented within our pre-fundamentals components library. 

![image](https://user-images.githubusercontent.com/5056972/51866404-c34a2f80-22fd-11e9-9150-78156daa8fc3.png)

see also:
https://github.com/SAP/fundamental-vue/issues/134
https://github.com/SAP/fundamental-ngx/issues/410

**Comment by chrismanciero** [comment]
I did some research into implementing **react-popper** on the Popover component and I came away with the notion that we may need to get the Fiori Fundamental design team involved to create new CSS styles for react-popper to work correctly. As well as the NGX and Vue teams since they may also face the same issues.

The body of the Popover component applies the CSS class`.fd-popover__body`. This class also applies a `:before` and `:after` pseudo-class to create the arrow that is displayed on the Popover component.

The issue I see is that the CSS styles create the arrow with the notion that the Popover will be below the DOM element that triggered it. 

Here is an example of the Popover with enough screen.
![screen shot 2019-02-07 at 6 53 31 pm](https://user-images.githubusercontent.com/38330612/52450965-3d06c800-2b0b-11e9-8c2a-54be5918bd36.png)

**react-popper** adds styling to the Popover component and updates a data-placement attribute when the Popover needs to be shifted correctly on the screen, but you can see from the current CSS styles the arrow in the Popover is not displayed correctly.
![screen shot 2019-02-07 at 6 53 42 pm](https://user-images.githubusercontent.com/38330612/52451011-61fb3b00-2b0b-11e9-96b7-44859f68d4de.png)

The same issues can be found when using **react-popper** to display the Popover component on the left or right side of a DOM element.

Off the top of my head a solution would be to create new CSS classes that look for the data-placement attribute applied to the Popover and display the arrow correctly. (A rule needs to be created for every combindation, top, bottom, top-right, etc)
Example:
`.fd-popover__body[data-placement="top"]::before`
`.fd-popover__body[data-placement="left"]::before`

It would be helpful if someone who was involved with using react-popper for the SAP Concur HIG library can provide some insight on this topic and point-out if I missed anything on getting react-popper to work with our Popover component.

**Comment by jbadan** [comment]
related to/probable fix for #450
