### ISSUE TITLE
form modal breaks docs when dismissed.

### ISSUE THREAD

**Issue by bcullman** [SAP/fundamental-react#462]
### Description
form modal breaks docs when dismissed.

### Versions
**fundamental-react:** 0.4.1
**fiori-fundamentals:** 1.4.2

![broke-modal](https://user-images.githubusercontent.com/5056972/53924151-c7b9e480-402f-11e9-9c2e-d0f5719cdc5b.gif)

**Comment by skvale** [comment]
This seems related to https://github.com/algolia/react-element-to-jsx-string/issues/344

Because the Form Modal has a React 16 ref (`this.txtEmailRef = React.createRef();`) on the `<input />` which ends up being passed to
`reactElementToJSXString` in the parent `<Example />` component.

Adding the prop `omitCodeSample` to the `<Example />` stops it from breaking, but isn't ideal.
