### ISSUE TITLE
Allow more types of props in <Button/> and <Modal/>

### ISSUE THREAD

**Issue by aerfio** [SAP/fundamental-react#544]
### Versions
**fundamental-react:**0.5.1
**fiori-fundamentals:**1.5.7

Could you please add more available `types` in Prop-types for `<Button/>`? Like `emphasized`, which works using fund-react, because it's in fiori, but prop-types throw warnings in console. 

`emphasized` is used here: https://sap.github.io/fundamental-react/button in first example, but here it's absent:

![image](https://user-images.githubusercontent.com/17271979/57410031-0152cb80-71ea-11e9-9e8b-fe9152e1e62f.png)

Same goes for `<Modal/>` but it's a stretch I think: would it be possible to extend prop-types for `title` to accept react nodes? Like here: 
![image](https://user-images.githubusercontent.com/17271979/57410164-61e20880-71ea-11e9-9a31-55715559e44e.png) (it works as it is now btw)

---

_**NOTE:** Where applicable, please include uncropped screen captures._

_**DISCLAIMER:**
After triaging an issue, the fundamental-react team will see if it can be reproduced or confirmed. If more information is needed, the fundamental-react team will contact the author.  Any issues awaiting responses from the author for more than 7 days will be closed.  The author can re-open the issue at a later time if they can present the requested information._

**Comment by jbadan** [comment]
Hi @aerfio!
For buttons, we have `emphasized` and `light` under proptype `option` instead of `type`. I see how this can be confusing, but they were separated out so that you could use them together with the other types - `standard`, `positive`, `negative`, `medium`. see: https://sap.github.io/fundamental-react/button#properties

Although, we should look into if we want to change this. 

For the modal, we do allow you to specify which heading level you would like to use via the `headingLevel` prop. We chose to limit this to `h2-h6`. 

Using a `<p>` tag would not be correct here.  Additionally, other tags have roles and we don’t allow nodes so that the heading doesn’t have incorrect nested roles. Our specs involve matching the output html from fiori-fundamental, which uses heading levels: https://sap.github.io/fundamental/components/modal.html.
