### ISSUE TITLE
Need to create onClick prop for tile component

### ISSUE THREAD

**Issue by hertweckhr1** [SAP/fundamental-react#554]
### Description
Adding the role="button" is adding some hover styling that would indicate the tile is clickable, however, there is nothing in the API that would handle that. It seems like an onClick prop should be passed, which then can add roles, aria labels, use different elements, etc.

### Versions
**fundamental-react:** 0.5.4
**fiori-fundamentals:** 1.5.8

**Comment by singh-mahendra** [comment]
Since the Tile Component is created with forwardRef, it is possible to add a click listener on the ref.
Along with the role,we also need to pass the tabIndex prop on the Tile component to show the hover outline on tab.Also,we need to add the 'enter' and 'space' listeners on the ref.
Please see the example FioriTile.js: https://codesandbox.io/s/spring-leftpad-nb7zv

**Comment by jbadan** [comment]
That's a good workaround, but it should be built into the props of the component.

**Comment by singh-mahendra** [comment]
Added the onClick,active and tabIndex prop on Tile Component.Please review the PR.
