### ISSUE TITLE
Unable to load the fundamental-styles from node_modules via webpack4

### ISSUE THREAD

**Issue by LawrenceBi** [SAP/fundamental-react#624]
### Description
Hi Team,

I try to playaround with "fundamental-react" library locally. Firstly I use "create-react-app" to generate initial React app and load "fundamental-styles" into App.css via adding following code, it works fine.
`@import '~fundamental-styles/dist/fundamental-styles-ie11.min.css';`

Then I use "webpack4" to generate initial React app and load "fundamental-styles" into created App.css https://github.wdf.sap.corp/I321528/my-react-app/blob/master/src/App.css. But an error occurs when the app runs on local server. Please kindly see the screenshot.
![image](https://user-images.githubusercontent.com/29089237/60008746-30909f80-96a7-11e9-84e0-3a1fc922d342.png)

I have uploaded all code of my playaround app into the repository https://github.wdf.sap.corp/I321528/my-react-app. Do you know how to fix this error? Many thanks!

Best Regards,
Lawrence

### Versions
**fundamental-react:**
**fundamental-styles:**

---

_**NOTE:** Where applicable, please include uncropped screen captures._

_**DISCLAIMER:**
After triaging an issue, the fundamental-react team will see if it can be reproduced or confirmed. If more information is needed, the fundamental-react team will contact the author.  Any issues awaiting responses from the author for more than 7 days will be closed.  The author can re-open the issue at a later time if they can present the requested information._

**Comment by jbadan** [comment]
Hello @LawrenceBi , what versions of fundamental-react and fundamental-styles are you using?

**Comment by jbadan** [comment]
So I just played around in your repo, the problem is this: https://github.wdf.sap.corp/I321528/my-react-app/blob/master/src/App.css#L1 and https://github.wdf.sap.corp/I321528/my-react-app/blob/master/package.json#L26

You have installed `fundamental-styles` but are trying to import from `fiori-fundamentals`. These are separate libraries. 

Use `@import '~fundamental-styles/dist/fundamental-styles-ie11.min.css';`

Please reopen the issue if you need more help :)
