### ISSUE TITLE
make a library for all the components

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-react#78]
The current repo doesn't expose the components as a library so they cannot be used in other projects.

**Comment by alexanderchan** [comment]
Hi guys, love what you're doing here and I'm really hoping this entire project moves forward.  I did notice that this is based off of create-react-app and it might be worth considering how other libraries are packaged as I am sure they have evolved to use best practices over the years.  

You could in fact take their build pipeline and adapt it instead of using create-react-app which I believe is more intended for actual applications and not ui libraries.

Here's some ideas to get you started:

https://github.com/reactstrap/reactstrap
https://github.com/atlassian/react-beautiful-dnd
https://github.com/palantir/blueprint
https://github.com/ReactTraining/react-router
https://github.com/mobxjs/mobx

come to mind as large well maintained libraries but there are no shortages out there.  I would hope to include sap/fundamental-react in my list one day and the way to hop to the front is by basing it off of the shoulders of giants.

My guess is we're going to have to eject from create-react-app but the good news is we can use other people's knowledge to get to an even better build system for libraries.

**Comment by jiawang1** [comment]
hi

I have created a folk repo and separated components library and example project. You can check my repo here [https://github.com/jiawang1/fundamental-react/tree/master](https://github.com/jiawang1/fundamental-react/tree/master) ,  (master branch) I changed project to monorepo and utilize lerna to help manage library version number and internal dependency. One subproject is fundamental-react, this is pure library for components, this project could be built to esm and umd, and published to npm. Another subproject is example.
You still can run example when develop new component, it could reflect you latest code change in fundamental-react.
 
You also can download library @jay.wang/fundamental-react from NPM. I have removed some unnecessary stuff from the module.
 And follow steps :
1. Install Fiori Fundamentals:
npm install --save fiori-fundamentals
3. Include the Fiori Fundamentals CSS in your React application. In your App.css or App.scss file include the following lines:
$fd-icons-path: "~fiori-fundamentals/scss/icons/";
$fd-fonts-path: "~fiori-fundamentals/scss/fonts/";
@import '../node_modules/fiori-fundamentals/scss/all.scss';
 
You can import component from ‘@jay.wang/fundamental-react’ in your project.
This is just POC, so I did not create PR. If you interested in this, let know, I can explain details or create separate commits to merge back.
I hope fundamental-react get matured someday can be applied into my projects to replace UI5.

**Comment by jbadan** [comment]
@droshev I believe this is complete, but we should find a way of saving @jiawang1 's comment for when we switch to Lerna eventually.

**Comment by droshev** [comment]
@jbadan yes, we did it but I agree with you. Maybe we can keep the issue so we can track @jiawang1 's comments
