### ISSUE TITLE
Consider Global State (Redux) 

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-react#94]
Having a state outside the component tree will allow us to access it from anywhere in the application. There will be a single source of truth. This way the application can always take control over the components.

**Comment by alexanderchan** [comment]
We want to avoid global state where possible and I'd consider using react context before redux to reduce the dependencies on other libraries.

**Comment by CodesOfRa** [comment]
thanks  @alexanderchan for your input , we are still discussing this topic.

**Comment by alexanderchan** [comment]
It seems that useReducer that will arrive with react hooks could provide some of the functionality of redux https://reactjs.org/docs/hooks-faq.html#how-to-avoid-passing-callbacks-down if we really need to be passing around state from upper levels to lower but I would wonder what the use case for state outside of the component tree is.  Do we have an example of where we would need the state? 

For most components I would expect to be able to pass in values via props.

**Comment by greg-a-smith** [comment]
I would echo and expand on @alexanderchan's comments.  Since components are not an application themselves, they should be "dumb" and accept props for any external state-like information.  This allows any external consumers to use them and doesn't get coupled with a specific dependency.  Components should ideally avoid state tracking entirely unless it's purely local state for the benefit of the component itself.

**Comment by bcullman** [comment]
Closing.

State should be managed by the application, not this component library.
